In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

In [5]:
df = pd.read_csv("CreditCardTransaction.csv")

In [6]:
from sklearn.ensemble import IsolationForest

In [7]:
features = df[['TrnxAmount']]

In [8]:
model = IsolationForest(
    contamination=0.01,
    random_state=42
)

df['anomaly'] = model.fit_predict(features)

In [9]:
df['anomaly'] = df['anomaly'].map({
    1:0,
    -1:1
})

In [10]:
df['anomaly'].value_counts()

anomaly
0    780692
1      7829
Name: count, dtype: int64

In [12]:
df[df['anomaly']==1][
    ['Department','Merchant','TrnxAmount']
].head(20)

                       Department                   Merchant  TrnxAmount
246                      JUDICIAL     CAN*CANONFINANCIAL CFS     5707.87
484                     EXECUTIVE       BOULEVARD AUTO SALES     5834.27
505                     EXECUTIVE      FRED DRAKE AUTOMOTIVE    14765.92
533                     EXECUTIVE      CHEVROLET OF DOVER II     8923.21
544                     EXECUTIVE         DIAMOND STATE TIRE     6023.18
554                     EXECUTIVE   WINNER PREMIER COLLISION    11146.92
561                     EXECUTIVE     E ZPASS DE CSC00100701    18575.00
563                     EXECUTIVE          B And G AUTO BODY     9640.13
567                     EXECUTIVE       BOULEVARD AUTO SALES     5710.03
782  DEPT OF TECHNOLOGY AND INFOR                     NASCIO     9000.00
789  DEPT OF TECHNOLOGY AND INFOR         VZWRLSS*MY VZ VB P     6395.49
793  DEPT OF TECHNOLOGY AND INFOR     VERIZON*ONETIMEPAYMENT    55924.80
825  DEPT OF TECHNOLOGY AND INFOR  CARAHSOFT TECHNOLOGY CORP    13029.20
833  DEPT OF TECHNOLOGY AND INFOR  CARAHSOFT TECHNOLOGY CORP    79306.34
840  DEPT OF TECHNOLOGY AND INFOR                    IBM IOL    10800.00
844  DEPT OF TECHNOLOGY AND INFOR                    IBM IOL    12542.24
845  DEPT OF TECHNOLOGY AND INFOR                    IBM IOL     6230.67
848  DEPT OF TECHNOLOGY AND INFOR                    IBM IOL    33717.67
880  DEPT OF TECHNOLOGY AND INFOR                    IBM IOL     6376.24
890  DEPT OF TECHNOLOGY AND INFOR     LEVEL 3 COMMUNICATIONS     6095.38

In [13]:
#merchant frequency
merchant_freq = df['Merchant'].value_counts()

df['MerchantFreq'] = df['Merchant'].map(
    merchant_freq
)

In [15]:
#department frequency
dept_freq = df['Department'].value_counts()

df['DeptFreq'] = df['Department'].map(
    dept_freq
)

In [20]:
df['TranxDate'] = pd.to_datetime(
    df['TranxDate'],
    errors='coerce'
)
df['TranxDate'].dtype

dtype('<M8[ns]')

In [21]:
df['TranxDate'].isna().sum()

np.int64(324016)

In [22]:
df['Weekday'] = df['TranxDate'].dt.dayofweek

In [23]:
df['Month_Num'] = df['TranxDate'].dt.month

In [24]:
df['TranxDate'].head()

0   2018-06-29
1          NaT
2          NaT
3   2018-06-30
4   2018-06-27
Name: TranxDate, dtype: datetime64[ns]

In [25]:
df['TranxDate'].dtype

dtype('<M8[ns]')

In [26]:
df['TranxDate'].isna().sum()

np.int64(324016)

In [27]:
raw_df = pd.read_csv("CreditCardTransaction.csv")

In [28]:
bad_dates = raw_df.loc[
    df['TranxDate'].isna(),
    'TranxDate'
]

bad_dates.head(20)

1      07-03-2018
2      07-01-2018
7      07-04-2018
12     07-12-2018
13     07-12-2018
17     07-07-2018
18     07-12-2018
34     07-11-2018
39     07-12-2018
42     07-07-2018
43     07-07-2018
44     07-04-2018
76     07-10-2018
77     07-11-2018
81     07-01-2018
82     07-10-2018
85     07-11-2018
99     07-12-2018
100    07-02-2018
103    07-12-2018
Name: TranxDate, dtype: object

In [29]:
df['TranxDate'] = pd.to_datetime(
    raw_df['TranxDate'],
    format='mixed',
    errors='coerce'
)

In [30]:
df['TranxDate'].isna().sum()

np.int64(0)

In [31]:
df['TranxDate'].isna().sum()

np.int64(0)

In [32]:
merchant_freq = df['Merchant'].value_counts()

df['MerchantFreq'] = df['Merchant'].map(merchant_freq)

In [33]:
dept_freq = df['Department'].value_counts()

df['DeptFreq'] = df['Department'].map(dept_freq)

In [34]:
features = df[
    [
        'TrnxAmount',
        'MerchantFreq',
        'DeptFreq',
        'Weekday',
        'Month_Num'
    ]
]

In [35]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(features)

In [36]:
from sklearn.ensemble import IsolationForest

model = IsolationForest(
    contamination=0.005,
    random_state=42
)

pred = model.fit_predict(X_scaled)

df['anomaly_v2'] = (pred == -1).astype(int)

In [37]:
df['anomaly_v2'].value_counts()

anomaly_v2
0    784579
1      3942
Name: count, dtype: int64

In [38]:
df[df['anomaly_v2']==1][
    ['Department',
     'Merchant',
     'TrnxAmount',
     'MerchantFreq',
     'DeptFreq']
].head(20)

,Department,Merchant,TrnxAmount,MerchantFreq,DeptFreq
196,JUDICIAL,CAN*CANONFINANCIAL CFS,4395.53,9247,19194
246,JUDICIAL,CAN*CANONFINANCIAL CFS,5707.87,9247,19194
833,DEPT OF TECHNOLOGY AND INFOR,CARAHSOFT TECHNOLOGY CORP,79306.34,19,6009
1065,STATE TREASURER,GRAINGER,43.63,16526,992
2289,DEPT OF FINANCE,GRAINGER,93.78,16526,5512
3416,SVS FR CHILDREN YOUTH FAMILIES,DMI* DELL HLTHCR/REL,26940.40,3629,38811
4755,DEPT OF CORRECTIONS,WB MASON,22141.20,3830,88181
4930,DEPT OF CORRECTIONS,THE CLASS PRODUCE GROUP,20608.64,237,88181
4953,DEPT OF CORRECTIONS,STATE JANITORAL SUPPLY,10407.70,5196,88181
4980,DEPT OF CORRECTIONS,STATE JANITORAL SUPPLY,15806.00,5196,88181
4993,DEPT OF CORRECTIONS,H. SCHRIER And CO. INC.,23830.21,718,88181
5029,DEPT OF CORRECTIONS,HY-POINT DAIRY FARMS INC,25938.68,2,88181
5440,DEPT OF CORRECTIONS,WASTE MGMT WM EZPAY,46204.93,3028,88181
5544,DEPT OF CORRECTIONS,BI INCORPORATED A,33147.30,104,88181
6501,DEPT OF NATRL RES AND ENV CONT,GRAINGER,186.72,16526,103248
7405,DEPT OF NATRL RES AND ENV CONT,GRAINGER,17.71,16526,103248
7707,DEPT OF NATRL RES AND ENV CONT,GRAINGER,59.60,16526,103248
8650,DEPT OF SAFETY AND HOMELAND,VZWRLSS*IVR VB,22555.57,2895,42074
8741,DEPT OF TRANSPORTATION,CAN*CANONFINANCIAL CFS,11410.21,9247,85203
8777,DEPT OF TRANSPORTATION,VZWRLSS*MY VZ VB P,52122.02,3334,85203

In [39]:
df['anomaly_score'] = model.decision_function(
    X_scaled
)

In [40]:
df['anomaly_score'].describe()

count    788521.000000
mean          0.132858
std           0.034485
min          -0.076495
25%           0.118401
50%           0.141392
75%           0.157460
max           0.176400
Name: anomaly_score, dtype: float64

In [41]:
df['risk_level'] = pd.cut(
    df['anomaly_score'],
    bins=[
        -1,
        -0.05,
        0,
        0.05,
        1
    ],
    labels=[
        'Critical',
        'High',
        'Medium',
        'Low'
    ]
)

In [42]:
dept_risk = (
    df.groupby('Department')
      .agg(
          Total_Transactions=('anomaly_v2','count'),
          Anomalies=('anomaly_v2','sum')
      )
)

In [43]:
dept_risk['Anomaly_Rate'] = (
    dept_risk['Anomalies']
    /
    dept_risk['Total_Transactions']
    *100
)

In [44]:
dept_risk.sort_values(
    'Anomaly_Rate',
    ascending=False
).head(20)

                                Total_Transactions  Anomalies  Anomaly_Rate
Department
STATE TREASURER                                992         50      5.040323
DEPT OF TECHNOLOGY AND INFOR                  6009        153      2.546181
DEPARTMENT OF HUMAN RESOURCES                 2291         56      2.444347
DEPT OF CORRECTIONS                          88181       1165      1.321146
LAS AMERICAS ASPIRA                           3578         35      0.978200
EXECUTIVE                                    17138        163      0.951103
DEPT OF TRANSPORTATION                       85203        768      0.901377
JUDICIAL                                     19194        145      0.755444
FIRE PREVENTION COMMISSION                    3626         22      0.606729
DEPT OF ELECTIONS                             2847         16      0.561995
DEPT OF FINANCE                               5512         30      0.544267
DEPT OF EDUCATION                             8326         44      0.528465
THOMAS A EDISON CHARTER SCHOOL                2397         12      0.500626
LEGAL                                        19413         90      0.463607
DEPT OF NATRL RES AND ENV CONT              103248        462      0.447466
DEPT OF STATE                                34606        150      0.433451
AUDITOR OF ACCOUNTS                           1014          4      0.394477
DEPT OF HEALTH AND SOCIAL SV                 58459        200      0.342120
DEPT OF AGRICULTURE                          13350         36      0.269663
WOODBRIDGE SCHOOL DISTRICT                    3206          8      0.249532

In [45]:
#Top Departments by Anomaly Rate
dept_risk.sort_values(
    'Anomaly_Rate',
    ascending=False
).head(15)

                                Total_Transactions  Anomalies  Anomaly_Rate
Department
STATE TREASURER                                992         50      5.040323
DEPT OF TECHNOLOGY AND INFOR                  6009        153      2.546181
DEPARTMENT OF HUMAN RESOURCES                 2291         56      2.444347
DEPT OF CORRECTIONS                          88181       1165      1.321146
LAS AMERICAS ASPIRA                           3578         35      0.978200
EXECUTIVE                                    17138        163      0.951103
DEPT OF TRANSPORTATION                       85203        768      0.901377
JUDICIAL                                     19194        145      0.755444
FIRE PREVENTION COMMISSION                    3626         22      0.606729
DEPT OF ELECTIONS                             2847         16      0.561995
DEPT OF FINANCE                               5512         30      0.544267
DEPT OF EDUCATION                             8326         44      0.528465
THOMAS A EDISON CHARTER SCHOOL                2397         12      0.500626
LEGAL                                        19413         90      0.463607
DEPT OF NATRL RES AND ENV CONT              103248        462      0.447466

In [46]:
#Top Merchants by Number of Anomalies
df[df['anomaly_v2']==1]\
.groupby('Merchant')\
.size()\
.sort_values(ascending=False)\
.head(20)

Merchant
GRAINGER                    2631
CAN*CANONFINANCIAL CFS       232
VERIZONWRLSS*RTCCR VB        147
CITY OF WILMINGTON            87
VERIZON*ONETIMEPAYMENT        82
H. SCHRIER And CO. INC.       56
DMI* DELL HLTHCR/REL          54
WASTE MGMT WM EZPAY           45
STATE JANITORAL SUPPLY        31
CITY OF WILM-DIV REVENUE      27
KARETAS FOODS                 20
BARR INTERNATIONAL            20
SCHMIDT BAKING CO.            19
GOOD SOURCE SOLUTIONS         18
VZWRLSS*IVR VB                18
HYPOINT DAIRY FARMS INC       18
THE CLASS PRODUCE GROUP       16
MTM TECHNOLOGIES INC          16
WB MASON                      14
ATLANTIC BEVERAGE             13
dtype: int64

In [47]:
grainger = df[df['Merchant']=="GRAINGER"]

grainger['TrnxAmount'].describe()

count    16526.000000
mean       257.235845
std        657.661276
min     -15547.160000
25%         34.112500
50%         90.930000
75%        247.637500
max      19986.440000
Name: TrnxAmount, dtype: float64

In [48]:
df.groupby('Year')['TrnxAmount'].sum()

Year
2019    73886994.50
2020    70939105.50
2021    68059922.62
2022    77081142.78
2023    48017420.30
Name: TrnxAmount, dtype: float64

In [49]:
df.groupby('Year')['anomaly_v2'].sum()

Year
2019    739
2020    951
2021    938
2022    999
2023    315
Name: anomaly_v2, dtype: int64

In [50]:
year_stats = df.groupby('Year').agg(
    Total_Spend=('TrnxAmount','sum'),
    Anomalies=('anomaly_v2','sum'),
    Transactions=('anomaly_v2','count')
)

year_stats['Anomaly_Rate'] = (
    year_stats['Anomalies'] /
    year_stats['Transactions']
) * 100

year_stats

      Total_Spend  Anomalies  Transactions  Anomaly_Rate
Year
2019  73886994.50        739        196806      0.375497
2020  70939105.50        951        179373      0.530180
2021  68059922.62        938        142303      0.659157
2022  77081142.78        999        163942      0.609362
2023  48017420.30        315        106097      0.296898

In [52]:
final_df = df[
    [
        'Year',
        'Month',
        'Department',
        'Division',
        'Merchant',
        'TranxDescription',
        'TranxDate',
        'TrnxAmount',
        'anomaly_v2',
        'anomaly_score'
    ]
]

final_df.to_csv(
    'powerbi.csv',
    index=False
)

In [53]:
df['Amount_Zscore_Department'] = (
    df.groupby('Department')['TrnxAmount']
      .transform(lambda x: (x - x.mean()) / x.std())
)

In [55]:
pip install streamlit plotly pandas numpy scikit-learn

Requirement already satisfied: streamlit in /opt/anaconda3/lib/python3.13/site-packages (1.45.1)
Requirement already satisfied: plotly in /opt/anaconda3/lib/python3.13/site-packages (5.24.1)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.1.3)
Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.13/site-packages (1.6.1)
Requirement already satisfied: altair<6,>=4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (8.1.8)
Requirement already satisfied: packaging<25,>=20 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (24.2)
Requirement already satisfied: pillow<12,>=7.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (11.1.0)
Requirement already satisfied: protobuf<7,>=3.20 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (19.0.0)
Requirement already satisfied: requests<3,>=2.27 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (4.12.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (3.1.43)
Requirement already satisfied: tornado<7,>=6.0.3 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (6.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.13/site-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /opt/anaconda3/lib/python3.13/site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in /opt/anaconda3/lib/python3.13/site-packages (from altair<6,>=4.0->streamlit) (1.31.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (2025.6.15)
Requirement already satisfied: scipy>=1.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [56]:
import streamlit as st
import pandas as pd

st.set_page_config(
    page_title="Credit Card Risk Dashboard",
    layout="wide"
)

st.title("Credit Card Transaction Risk Analytics Dashboard")

2026-06-05 13:50:34.662 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-05 13:50:34.662 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-05 13:50:34.689
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /opt/anaconda3/lib/python3.13/site-packages/ipykernel_launcher.py [ARGUMENTS]
2026-06-05 13:50:34.689 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [58]:
@st.cache_data
def load_data():
    return pd.read_csv("powerbi.csv")

df = load_data()

2026-06-05 13:51:38.349 No runtime found, using MemoryCacheStorageManager
2026-06-05 13:51:38.351 No runtime found, using MemoryCacheStorageManager
2026-06-05 13:51:38.352 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-05 13:51:38.352 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-05 13:51:38.353 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-05 13:51:38.868 Thread 'Thread-6': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-05 13:51:38.876 Thread 'Thread-6': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-05 13:51:38.876 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-05 13:51:38.876 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [59]:
st.write(df.head())

2026-06-05 13:51:51.773 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-05 13:51:51.773 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.